package com.cia.persistencia;
// Generated 29/11/2018 07:18:52 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * CiaDetalleCursos generated by hbm2java
 */
public class CiaDetalleCursos  implements java.io.Serializable {


     private BigDecimal dcrId;
     private CiaCursos ciaCursos;
     private CiaInfracciones ciaInfracciones;
     private BigDecimal dcrEstado;
     private Date dcrFechaEstado;

    public CiaDetalleCursos() {
    }

	
    public CiaDetalleCursos(BigDecimal dcrId) {
        this.dcrId = dcrId;
    }
    public CiaDetalleCursos(BigDecimal dcrId, CiaCursos ciaCursos, CiaInfracciones ciaInfracciones, BigDecimal dcrEstado, Date dcrFechaEstado) {
       this.dcrId = dcrId;
       this.ciaCursos = ciaCursos;
       this.ciaInfracciones = ciaInfracciones;
       this.dcrEstado = dcrEstado;
       this.dcrFechaEstado = dcrFechaEstado;
    }
   
    public BigDecimal getDcrId() {
        return this.dcrId;
    }
    
    public void setDcrId(BigDecimal dcrId) {
        this.dcrId = dcrId;
    }
    public CiaCursos getCiaCursos() {
        return this.ciaCursos;
    }
    
    public void setCiaCursos(CiaCursos ciaCursos) {
        this.ciaCursos = ciaCursos;
    }
    public CiaInfracciones getCiaInfracciones() {
        return this.ciaInfracciones;
    }
    
    public void setCiaInfracciones(CiaInfracciones ciaInfracciones) {
        this.ciaInfracciones = ciaInfracciones;
    }
    public BigDecimal getDcrEstado() {
        return this.dcrEstado;
    }
    
    public void setDcrEstado(BigDecimal dcrEstado) {
        this.dcrEstado = dcrEstado;
    }
    public Date getDcrFechaEstado() {
        return this.dcrFechaEstado;
    }
    
    public void setDcrFechaEstado(Date dcrFechaEstado) {
        this.dcrFechaEstado = dcrFechaEstado;
    }




}


