package com.cia.persistencia;
// Generated 29/11/2018 07:18:52 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CiaInfracciones generated by hbm2java
 */
public class CiaInfracciones implements java.io.Serializable {

    private BigDecimal infId;
    private CiaPersonas ciaPersonas;
    private CiaUsuarios ciaUsuarios;
    private String infCodigo;
    private Date infFecha;
    private String infFactura;
    private BigDecimal infEstado;
    private Date infFechaEstado;
    private Date infFacFecha;
    private String infNumero;
    private BigDecimal infvalorCurso;
    private Set ciaDetalleCursoses = new HashSet(0);

    public CiaInfracciones() {
    }

    public CiaInfracciones(BigDecimal infId, CiaPersonas ciaPersonas, CiaUsuarios ciaUsuarios, String infCodigo, String infFactura, BigDecimal infEstado, BigDecimal valorCurso) {
        this.infId = infId;
        this.ciaPersonas = ciaPersonas;
        this.ciaUsuarios = ciaUsuarios;
        this.infCodigo = infCodigo;
        this.infFactura = infFactura;
        this.infEstado = infEstado;
        this.infvalorCurso = valorCurso;
    }

    public CiaInfracciones(BigDecimal infId, CiaPersonas ciaPersonas, CiaUsuarios ciaUsuarios, String infCodigo, Date infFecha, String infFactura, BigDecimal infEstado, Date infFechaEstado, String infNumero, BigDecimal valorCurso, Set ciaDetalleCursoses) {
        this.infId = infId;
        this.ciaPersonas = ciaPersonas;
        this.ciaUsuarios = ciaUsuarios;
        this.infCodigo = infCodigo;
        this.infFecha = infFecha;
        this.infFactura = infFactura;
        this.infEstado = infEstado;
        this.infFechaEstado = infFechaEstado;
        this.infNumero = infNumero;
        this.infvalorCurso = valorCurso;
        this.ciaDetalleCursoses = ciaDetalleCursoses;
    }

    public BigDecimal getInfId() {
        return this.infId;
    }

    public void setInfId(BigDecimal infId) {
        this.infId = infId;
    }

    public CiaPersonas getCiaPersonas() {
        return this.ciaPersonas;
    }

    public void setCiaPersonas(CiaPersonas ciaPersonas) {
        this.ciaPersonas = ciaPersonas;
    }

    public CiaUsuarios getCiaUsuarios() {
        return this.ciaUsuarios;
    }

    public void setCiaUsuarios(CiaUsuarios ciaUsuarios) {
        this.ciaUsuarios = ciaUsuarios;
    }

    public String getInfCodigo() {
        return this.infCodigo;
    }

    public void setInfCodigo(String infCodigo) {
        this.infCodigo = infCodigo;
    }

    public Date getInfFecha() {
        return this.infFecha;
    }

    public void setInfFecha(Date infFecha) {
        this.infFecha = infFecha;
    }

    public String getInfFactura() {
        return this.infFactura;
    }

    public void setInfFactura(String infFactura) {
        this.infFactura = infFactura;
    }

    public BigDecimal getInfEstado() {
        return this.infEstado;
    }

    public void setInfEstado(BigDecimal infEstado) {
        this.infEstado = infEstado;
    }

    public Date getInfFechaEstado() {
        return this.infFechaEstado;
    }

    public void setInfFechaEstado(Date infFechaEstado) {
        this.infFechaEstado = infFechaEstado;
    }

    public String getInfNumero() {
        return this.infNumero;
    }

    public void setInfNumero(String infNumero) {
        this.infNumero = infNumero;
    }

    public Set getCiaDetalleCursoses() {
        return this.ciaDetalleCursoses;
    }

    public void setCiaDetalleCursoses(Set ciaDetalleCursoses) {
        this.ciaDetalleCursoses = ciaDetalleCursoses;
    }

    /**
     * @return the infvalorCurso
     */
    public BigDecimal getInfvalorCurso() {
        return infvalorCurso;
    }

    /**
     * @param infvalorCurso the infvalorCurso to set
     */
    public void setInfvalorCurso(BigDecimal infvalorCurso) {
        this.infvalorCurso = infvalorCurso;
    }

    /**
     * @return the infFacFecha
     */
    public Date getInfFacFecha() {
        return infFacFecha;
    }

    /**
     * @param infFacFecha the infFacFecha to set
     */
    public void setInfFacFecha(Date infFacFecha) {
        this.infFacFecha = infFacFecha;
    }

}
