package com.cia.persistencia;
// Generated 29/11/2018 07:18:52 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CiaPersonas generated by hbm2java
 */
public class CiaPersonas implements java.io.Serializable {

    private BigDecimal perId;
    private String perNombres;
    private String perApellidos;
    private BigDecimal perTpDocumento;
    private String perDocumento;
    private BigDecimal perTelefono;
    private String perDireccion;
    private BigDecimal perEstado;
    private Date perFechaEstado;
    private Set ciaUsuarioses = new HashSet(0);
    private Set ciaCursoses = new HashSet(0);
    private Set ciaInfraccioneses = new HashSet(0);

    public CiaPersonas() {
    }

    public CiaPersonas(BigDecimal perId) {
        this.perId = perId;
    }

    public CiaPersonas(BigDecimal perId, String perNombres, String perApellidos, BigDecimal perTpDocumento, String perDocumento, BigDecimal perEstado) {
        this.perId = perId;
        this.perNombres = perNombres;
        this.perApellidos = perApellidos;
        this.perTpDocumento = perTpDocumento;
        this.perDocumento = perDocumento;
        this.perEstado = perEstado;
    }

    public CiaPersonas(BigDecimal perId, String perNombres, String perApellidos, BigDecimal perTpDocumento, String perDocumento, BigDecimal perTelefono, String perDireccion, BigDecimal perEstado, Date perFechaEstado, Set ciaUsuarioses, Set ciaCursoses, Set ciaInfraccioneses) {
        this.perId = perId;
        this.perNombres = perNombres;
        this.perApellidos = perApellidos;
        this.perTpDocumento = perTpDocumento;
        this.perDocumento = perDocumento;
        this.perTelefono = perTelefono;
        this.perDireccion = perDireccion;
        this.perEstado = perEstado;
        this.perFechaEstado = perFechaEstado;
        this.ciaUsuarioses = ciaUsuarioses;
        this.ciaCursoses = ciaCursoses;
        this.ciaInfraccioneses = ciaInfraccioneses;
    }

    public BigDecimal getPerId() {
        return this.perId;
    }

    public void setPerId(BigDecimal perId) {
        this.perId = perId;
    }

    public String getPerNombres() {
        return this.perNombres;
    }

    public void setPerNombres(String perNombres) {
        this.perNombres = perNombres;
    }

    public String getPerApellidos() {
        return this.perApellidos;
    }

    public void setPerApellidos(String perApellidos) {
        this.perApellidos = perApellidos;
    }

    public BigDecimal getPerTpDocumento() {
        return this.perTpDocumento;
    }

    public void setPerTpDocumento(BigDecimal perTpDocumento) {
        this.perTpDocumento = perTpDocumento;
    }

    public String getPerDocumento() {
        return this.perDocumento;
    }

    public void setPerDocumento(String perDocumento) {
        this.perDocumento = perDocumento;
    }

    public BigDecimal getPerTelefono() {
        return this.perTelefono;
    }

    public void setPerTelefono(BigDecimal perTelefono) {
        this.perTelefono = perTelefono;
    }

    public String getPerDireccion() {
        return this.perDireccion;
    }

    public void setPerDireccion(String perDireccion) {
        this.perDireccion = perDireccion;
    }

    public BigDecimal getPerEstado() {
        return this.perEstado;
    }

    public void setPerEstado(BigDecimal perEstado) {
        this.perEstado = perEstado;
    }

    public Date getPerFechaEstado() {
        return this.perFechaEstado;
    }

    public void setPerFechaEstado(Date perFechaEstado) {
        this.perFechaEstado = perFechaEstado;
    }

    public Set getCiaUsuarioses() {
        return this.ciaUsuarioses;
    }

    public void setCiaUsuarioses(Set ciaUsuarioses) {
        this.ciaUsuarioses = ciaUsuarioses;
    }

    public Set getCiaCursoses() {
        return this.ciaCursoses;
    }

    public void setCiaCursoses(Set ciaCursoses) {
        this.ciaCursoses = ciaCursoses;
    }

    public Set getCiaInfraccioneses() {
        return this.ciaInfraccioneses;
    }

    public void setCiaInfraccioneses(Set ciaInfraccioneses) {
        this.ciaInfraccioneses = ciaInfraccioneses;
    }

}
