package com.cia.persistencia;
// Generated 29/11/2018 07:18:52 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * CiaRecursosUsuarios generated by hbm2java
 */
public class CiaRecursosUsuarios  implements java.io.Serializable {


     private CiaRecursosUsuariosId id;
     private CiaRecursos ciaRecursos;
     private CiaUsuarios ciaUsuarios;
     private BigDecimal rusEstado;
     private Date rusFechaEstado;

    public CiaRecursosUsuarios() {
    }

	
    public CiaRecursosUsuarios(CiaRecursosUsuariosId id, CiaRecursos ciaRecursos, CiaUsuarios ciaUsuarios, BigDecimal rusEstado) {
        this.id = id;
        this.ciaRecursos = ciaRecursos;
        this.ciaUsuarios = ciaUsuarios;
        this.rusEstado = rusEstado;
    }
    public CiaRecursosUsuarios(CiaRecursosUsuariosId id, CiaRecursos ciaRecursos, CiaUsuarios ciaUsuarios, BigDecimal rusEstado, Date rusFechaEstado) {
       this.id = id;
       this.ciaRecursos = ciaRecursos;
       this.ciaUsuarios = ciaUsuarios;
       this.rusEstado = rusEstado;
       this.rusFechaEstado = rusFechaEstado;
    }
   
    public CiaRecursosUsuariosId getId() {
        return this.id;
    }
    
    public void setId(CiaRecursosUsuariosId id) {
        this.id = id;
    }
    public CiaRecursos getCiaRecursos() {
        return this.ciaRecursos;
    }
    
    public void setCiaRecursos(CiaRecursos ciaRecursos) {
        this.ciaRecursos = ciaRecursos;
    }
    public CiaUsuarios getCiaUsuarios() {
        return this.ciaUsuarios;
    }
    
    public void setCiaUsuarios(CiaUsuarios ciaUsuarios) {
        this.ciaUsuarios = ciaUsuarios;
    }
    public BigDecimal getRusEstado() {
        return this.rusEstado;
    }
    
    public void setRusEstado(BigDecimal rusEstado) {
        this.rusEstado = rusEstado;
    }
    public Date getRusFechaEstado() {
        return this.rusFechaEstado;
    }
    
    public void setRusFechaEstado(Date rusFechaEstado) {
        this.rusFechaEstado = rusFechaEstado;
    }




}


