package com.cia.persistencia;
// Generated 29/11/2018 07:18:52 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * CiaRecursos generated by hbm2java
 */
public class CiaRecursos  implements java.io.Serializable {


     private BigDecimal recId;
     private String recNombre;
     private String recPath;
     private BigDecimal recEstado;
     private BigDecimal recFechaEstado;
     private Set ciaRecursosUsuarioses = new HashSet(0);

    public CiaRecursos() {
    }

	
    public CiaRecursos(BigDecimal recId, String recNombre, String recPath, BigDecimal recEstado) {
        this.recId = recId;
        this.recNombre = recNombre;
        this.recPath = recPath;
        this.recEstado = recEstado;
    }
    public CiaRecursos(BigDecimal recId, String recNombre, String recPath, BigDecimal recEstado, BigDecimal recFechaEstado, Set ciaRecursosUsuarioses) {
       this.recId = recId;
       this.recNombre = recNombre;
       this.recPath = recPath;
       this.recEstado = recEstado;
       this.recFechaEstado = recFechaEstado;
       this.ciaRecursosUsuarioses = ciaRecursosUsuarioses;
    }
   
    public BigDecimal getRecId() {
        return this.recId;
    }
    
    public void setRecId(BigDecimal recId) {
        this.recId = recId;
    }
    public String getRecNombre() {
        return this.recNombre;
    }
    
    public void setRecNombre(String recNombre) {
        this.recNombre = recNombre;
    }
    public String getRecPath() {
        return this.recPath;
    }
    
    public void setRecPath(String recPath) {
        this.recPath = recPath;
    }
    public BigDecimal getRecEstado() {
        return this.recEstado;
    }
    
    public void setRecEstado(BigDecimal recEstado) {
        this.recEstado = recEstado;
    }
    public BigDecimal getRecFechaEstado() {
        return this.recFechaEstado;
    }
    
    public void setRecFechaEstado(BigDecimal recFechaEstado) {
        this.recFechaEstado = recFechaEstado;
    }
    public Set getCiaRecursosUsuarioses() {
        return this.ciaRecursosUsuarioses;
    }
    
    public void setCiaRecursosUsuarioses(Set ciaRecursosUsuarioses) {
        this.ciaRecursosUsuarioses = ciaRecursosUsuarioses;
    }




}


