package com.cia.persistencia;
// Generated 29/11/2018 07:18:52 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * CiaRecursosUsuariosId generated by hbm2java
 */
public class CiaRecursosUsuariosId  implements java.io.Serializable {


     private BigDecimal usId;
     private BigDecimal recId;

    public CiaRecursosUsuariosId() {
    }

    public CiaRecursosUsuariosId(BigDecimal usId, BigDecimal recId) {
       this.usId = usId;
       this.recId = recId;
    }
   
    public BigDecimal getUsId() {
        return this.usId;
    }
    
    public void setUsId(BigDecimal usId) {
        this.usId = usId;
    }
    public BigDecimal getRecId() {
        return this.recId;
    }
    
    public void setRecId(BigDecimal recId) {
        this.recId = recId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CiaRecursosUsuariosId) ) return false;
		 CiaRecursosUsuariosId castOther = ( CiaRecursosUsuariosId ) other; 
         
		 return ( (this.getUsId()==castOther.getUsId()) || ( this.getUsId()!=null && castOther.getUsId()!=null && this.getUsId().equals(castOther.getUsId()) ) )
 && ( (this.getRecId()==castOther.getRecId()) || ( this.getRecId()!=null && castOther.getRecId()!=null && this.getRecId().equals(castOther.getRecId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUsId() == null ? 0 : this.getUsId().hashCode() );
         result = 37 * result + ( getRecId() == null ? 0 : this.getRecId().hashCode() );
         return result;
   }   


}


